# Generated by Django 4.0.6 on 2022-08-12 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_alter_film_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Favourite', models.BooleanField(default=True, verbose_name='фаворит')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourits', to='movies.film')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
