# Generated by Django 4.0.6 on 2022-08-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourits', to='movies.film', verbose_name='film'),
        ),
    ]
