# Generated by Django 4.0.6 on 2022-08-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_favourite_film'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='Favourite',
            new_name='favourite',
        ),
    ]
